# Site settings
title: *folio
email: james2.huxtable@uwe.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  My portfolio and Dev Blog.
baseurl: "/folio" # the subpath of your site, e.g. /blog/
url: https://huxyuk.github.io  # the base hostname & protocol for your site
twitter_username: huxyuk
github_username:  huxyuk

# SASS directory
sass:
   sass_dir: ./_sass/
    
# Build settings
markdown: kramdown
hightlighter: 'rouge' 
plugins: [jekyll-paginate]

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: false
    permalink: /poetry/:path/


